
import 'package:flutter/material.dart';

class HomeScreenLocationSearch extends StatefulWidget {
  const HomeScreenLocationSearch({Key? key}) : super(key: key);

  @override
  State<HomeScreenLocationSearch> createState() => _HomeScreenLocationSearchState();
}

class _HomeScreenLocationSearchState extends State<HomeScreenLocationSearch> {


  List<String> popularCities =[
    "Peshawar",
    "Peshawar",
    "Quetta",
    "Islamabad",
    "Karachi",
    "Lahore",
    "Lahore",

  ];
  List<String> otherCities =[
    "Abbottabad",
    "Attock",
    "Bahawalpur",
    "Chakwal",
    "D.G.Khan",
    "Faisalabad",
    "Gujranwala",
    "Gujrat",
    "Hyderabad",

    "Jhelum",
    "Karachi",
    "Lahore",
    "Multan",
    "Mardan",
    "Mandi bahauddin",
    "Mansehra",
    "Mirpur A.K.",
    "Nowshera",
    "Okara",
    "Peshawar",
    "Quetta",

    "Rahim Yar Khan",
    "Sialkot",
    "Sargodha",
    "Sahiwal",
    "Swabi",
    "Sheikhupura",
    "Wah cantt",

    //City Area of Rawalpindi:
    "Afshan Colony",
    "Air Force Housing Society",
    "Airport Housing Society",
    "Akalgarh",
    "Adiala Road",
    "AWT Housing Scheme",
    "Affandi Colony",
    "Al Jannat Garden",
    "Al-Haram City",
    "Allama Iqbal Colony",
    "Army Officers Colony",
    "Asghar MBuy Road",
    "Asia Housing Scheme",
    "Askari 1",
    "Askari 2",
    "Askari 3",
    "Askari 4",
    "Askari 5",
    "Askari 9",
    "Askari 10",
    "Askari 12",
    "Askari 13",
    "Askari-7",
    "Askari-11",
    "Askari-14",
    "Awan Town",
    "Ayub National Park",
    "Bahria Town Rawalpindi",
    "Babar Colony",
    "Bank Road",
    "Bankers Colony",
    "Banni Chowk",
    "Bostan Road",
    "Burma Town",
    "Buyama Iqbal Colony",
    "Chaklala",
    "Chaklala Scheme",
    "Chakri Road",
    "Chandni Chowk",
    "Caltex Road",
    "Cantt",
    "Chak Beli Khan",
    "Chakbeli Road",
    "Chanman Abad",
    "Chaudhary Jan Colony",
    "City Farm Houses",
    "City Villas",
    "Committee Chowk",
    "Cricket Stadium Road",
    "Danial Town",
    "Defence Colony",
    "Defence Road",
    "Dhamyal Road",
    "Dheri Hassanabad",
    "Dhok Chiragh Din",
    "Dhok Elahi Baksh",
    "Dhok Kala Khan",
    "Dhok Kashmirian",
    "Dhok Mangtal",
    "Dhok Paracha",
    "Dhok Piran Faqiran",
    "Dhok Sayedan Road",
    "Dhoke Hameeda",
    "Engineering Cooperative Housing Scheme",
    "Faizabad",
    "Farooq-e-Azam Road",
    "Fazaia Colony",
    "Fazal Town",
    "G.H.Q",
    "Gawal Mandi",
    "Ghauri Town",
    "Ghousia Colony",
    "Girja Road",
    "Gulistan Colony",
    "Gulrez Housing Scheme",
    "Gulshan Abad",
    "Gulshan Dadan",
    "Gulshan-e-Kashmir",
    "Gulshan-e-Khudadad",
    "Gulzar-e-Quaid Housing Society",
    "Hakim Muhammad Ajmal Khan Road",
    "Harley Street",
    "High Court Road",
    "Jahangir Road",
    "Janjua Town",
    "Jhanda Chichi",
    "Judicial Colony",
    "KRL Road",
    "Kahuta Road",
    "Kallar Syedan",
    "Kamala Abad",
    "Karor Lal Esan",
    "Kashmir Model Town",
    "Khanna Pul",
    "Khayaban-e-Sir-Syed",
    "Khurram Colony",
    "Kurri Road",
    "Lalazar",
    "Lalkurti",
    "Liaquat Bagh",
    "Main GT road",
    "Mall Road",
    "Mandra",
    "Marir",
    "Media Town",
    "Millat Colony",
    "Misryal Road",
    "Mohalla Banni",
    "Mohan Pura",
    "Morgah",
    "Mughalabad",
    "Mulpur",
    "Munawar Colony",
    "Murree Road",
    "Muslim Town",
    "Nanak Pura",
    "National Garden Housing Scheme",
    "National Town",
    "New Airport Town",
    "New Lalazar",
    "Ojhary Camp",
    "Old Punjab House",
    "PAF Residential Area",
    "PIA Colony",
    "PWD Colony",
    "Pakistan Town",
    "Pandora",
    "Peshawar Road",
    "Pir Wadhai",
    "Police Foundation Housing Scheme",
    "Quaid-e-Azam Colony",
    "Qurtaba City",
    "RCCI",
    "Race Course",
    "Rail View Housing Society",
    "Railway Workshop Road",
    "Raja Bazar",
    "Range Road",
    "Ranial",
    "Rawat Industrial Estate",
    "Saddar",
    "Satellite Town",
    "Sadiq Abad",
    "Safari Valley",
    "Safari View Residencia",
    "Saidpur Road",
    "Samarzar Housing Society",
    "Sangar Town",
    "Shah Khalid Colony",
    "Shaheen Town",
    "Shakrial",
    "Shalley Valley",
    "Shams Abad",
    "Sher Zaman Colony",
    "Supreme Court Employees Housing Society",
    "Swan Garden",
    "T Colony",
    "Takht Pari",
    "Tanch Bhata",
    "Tulsa Road",
    "Westridge",
    "Walait Homes",
    "Waris Khan",
    "Zeeshan Colony",

    //City Area of Islamabad:
    "7th Avenue",
    "9th Avenue",
    "AGHOSH",
    "AWT",
    "Aabpara Market",
    "Abbas Pura",
    "Abdullah Garden",
    "Agha Shahi Avenue",
    "Ahmed Town",
    "Airline Avenue",
    "Airport Enclave",
    "Akbar Town",
    "Alhamra Avenue",
    "AliPur",
    "Alipur Farash",
    "Anchorage Naval Housing scheme",
    "Angoori Road",
    "Arsalan Town",
    "Atomic Energy Employee Society",
    "Bahria Town",
    "Blue Area",
    "B-17",
    "Bahria Enclave",
    "Bani Gala",
    "Bhara kahu",
    "Bilal Town",
    "British Homes Colony",
    "Burma Town",
    "C-15",
    "C-16",
    "C-18",
    "C-19",
    "CBR Town",
    "Cantt",
    "Canyon Views",
    "Capital Enclave",
    "Capital Territory",
    "Chak Shahzad",
    "Chaklala Scheme",
    "Chatha Bakhtawar",
    "Chistiya Mohalla",
    "Civic Centre",
    "Civil Line",
    "Club Road",
    "Commoners Flower Velley",
    "Constitution Avenue",
    "D-12",
    "D-13",
    "D-14",
    "D-16",
    "D-17",
    "D-18",
    "DHA Defence",
    "DHA Valley",
    "Darussalam Co-Op Society",
    "Defence Phase-2",
    "Defence Phase-I",
    "Dhok Abdullah",
    "Dhok Chaudhrian",
    "Dhok Ghulam Mustafa",
    "Dhok Jumma",
    "Dhok Muqarab",
    "Diplomatic Enclave",
    "Dohk Ferdos",
    "E-6",
    "E-7",
    "E-8",
    "E-11",
    "E-12",
    "E-13",
    "E-14",
    "E-16",
    "E-17",
    "E-18",
    "E-19",
    "Eden Life Islamabad",
    "Embassy Road",
    "Engineering Co-operative Housing (ECHS)",
    "Engineers Cooperative Housing Society",
    "F-5",
    "F-6",
    "F-7",
    "F-8",
    "F-9",
    "F-13",
    "F-14",
    "F-15",
    "F-16",
    "F-10",
    "F-11",
    "F-17",
    "FECHS",
    "FOECHS-ForeignOfficeEmployeesSociety",
    "Faisal Town-F-18",
    "Fateh Jhang",
    "Fatima Town",
    "G-5",
    "G-6",
    "G-7",
    "G-8",
    "G-9",
    "G-10",
    "G-11",
    "G-12",
    "G-13",
    "G-14",
    "G-15",
    "G-16",
    "G-17",
    "G.H.Q Islamabad",
    "G.T Road Rawalpindi",
    "Ghauri Town",
    "Graceland Housing",
    "Green Avenue",
    "Gulberg",
    "Gulshan Town",
    "Gulzar Housing Scheme",
    "H-11",
    "H-12",
    "H-13",
    "H-15",
    "H-8",
    "H-9",
    "Humak",
    "I-9",
    "I-10",
    "I-8",
    "I-11",
    "I-12",
    "I-13",
    "I-14",
    "I-15",
    "I-16",
    "I-17",
    "I.J.P Road",
    "Islamabad Airport",
    "Islamabad Cooperative Housing",
    "Islamabad Enclave",
    "Islamabad Expressway",
    "Islamabad Highway",
    "Islamabad View VBuyey",
    "J and K Zone-V",
    "Jada",
    "Jamil Town",
    "Japan Road",
    "Jeddah Town",
    "Jhang Syedan",
    "Jhangi Syedan",
    "Jinnah Avenue",
    "Jinnah Garden",
    "Jinnah Super Market",
    "Jinnah Town",
    "Judicial Town",
    "Kahuta",
    "Kahuta Triangle Industrial Area",
    "Kala Gujran",
    "Karakoram Diplomatic Enclave",
    "Kashmir Colony",
    "Kashmir Highway",
    "Khayaban-e-Iqbal",
    "Koral Town",
    "Korang Town",
    "Kuri Model Town",
    "Lawyers Society",
    "Lehtarar Road",
    "Luqman Hakeem Road",
    "Machine Mohalla",
    "Mahandi Shah",
    "Malot",
    "Malpur",
    "MargBuya VBuyey-C-12",
    "Margalla Town",
    "Melody Market",
    "Ministry of Commerce Society",
    "Mohallah Mouhammadi Chowk",
    "Mohallah Shadab Road",
    "Motorway City",
    "Multi Resencia&Orchards",
    "Mumtaz City",
    "Muree Expressway",
    "Muzafar Town",
    "NHA Housing Society",
    "National Cooperative Housing Society",
    "National Police Foundation",
    "Naval Anchorage",
    "Naval Farms",
    "Nawaz Shaheed Colony",
    "New Airport Town",
    "New Shakrial",
    "O-9",
    "OPF VBuyey",
    "Orchard Scheme",
    "P.W.D Housing Scheme",
    "PAEC Employees Cooperative Housing Society",
    "PAF Tarnol",
    "PECHS",
    "PTV Colony",
    "Pakistan Housing Society",
    "Pakistan Town",
    "Park Enclave CDA",
    "Park Road",
    "Peraghab",
    "Pir Sohawa",
    "Pira Ghaib",
    "Ram Deen Bazar",
    "Rawal Dam",
    "Rawal Town",
    "Rawat",
    "River Garden",
    "Roshan Pakistan Scheme",
    "Royal City",
    "Sahil Colony",
    "Sangjani",
    "Sarai Alamgir",
    "Sawan Garden",
    "Shah Buyah Ditta",
    "Shah Dara",
    "Shamali Mohalla",
    "Shehzad Town",
    "Sihala",
    "Simly Dam Road",
    "Soan Garden",
    "Sohan Valley",
    "Spring Valley",
    "Sultan Pura",
    "Super Market",
    "Taramrri",
    "Tarlai",
    "Tarnol",
    "Thanda Pani",
    "The Springs",
    "Top City",
    "University Town",
    "Wapda Town",
    "Zaraj Housing Scheme",
    "Zero Point",

  ];
  var allCityList =[];
  var textEditingController = TextEditingController();
  var searchedCities = [];

  @override
  void initState() {
    allCityList.addAll(popularCities+otherCities);
    super.initState();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Container(
          padding: EdgeInsets.all(10),
          child: Column(

            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Select City',style: TextStyle(fontSize: 15,fontWeight: FontWeight.w500),),
              SizedBox(height: 5,),
              Divider(thickness: 2,color: Colors.grey,),
              Container(

                decoration: BoxDecoration(
                  color:Color(0xFFEFEFEF),
                  borderRadius: BorderRadius.circular(7)
                ),
                child: TextFormField(
                  controller: textEditingController,
                  onChanged: (value){
                    setState(() {
                      searchedCities=allCityList.where((city) => city.toLowerCase().contains(value.toLowerCase())).toList();

                    });
                  },
                  decoration: InputDecoration(
                    prefixIcon: Icon(Icons.search),
                    hintText: 'Type to refine search',
                    border: InputBorder.none
                  ),
                ),
              ),
              SizedBox(height: 10,),
              Text('All Cities',style: TextStyle(fontSize: 15,fontWeight: FontWeight.w500),),
              Divider(thickness: 1.5,),
              Text('Popular Cities',style: TextStyle(fontSize: 16,fontWeight: FontWeight.bold,color: Colors.blue),),
              Divider(),
              Expanded(
                child: textEditingController.text.isNotEmpty &&
                    searchedCities.isEmpty
                    ? Center(
                  child: Text('No Record Found'),
                             )
                    : ListView.separated(
                  physics: BouncingScrollPhysics(),
                      //shrinkWrap: true,

                  itemBuilder: (context, index) {

                      if(index==5){
                        return Text('Others Cities',style: TextStyle(fontSize: 16,fontWeight: FontWeight.bold,color: Colors.blue),);
                      }

                    return ListTile(
                      visualDensity: VisualDensity(vertical: -4),
                      onTap: () {
                       String city =textEditingController.text.isNotEmpty?searchedCities[index]:allCityList[index];
                       Navigator.pop(context,city);

                      },
                      leading: Text(textEditingController.text.isNotEmpty?searchedCities[index]:allCityList[index]),

                    );
                  },
                  separatorBuilder: (context, index) => Divider(
                    color: Colors.grey,
                  ),
                  itemCount: textEditingController.text.isNotEmpty?searchedCities.length:allCityList.length,),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
